openapi: 3.0.0
info:
  title: Translation API
  version: 1.0.0
  description: API for translation
paths:
  /translations:
    get:
      summary: Translation list
      parameters:
        - name: locale
          in: query
          required: false
          schema:
            type: string
            description: Locale
            default: en_GB
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Translation'

  /translation/{key}:
    get:
      summary: Get translation by key
      parameters:
        - name: key
          in: path
          required: true
          schema:
            type: string
            description: Translation key
        - name: locale
          in: query
          required: false
          schema:
            type: string
            description: Locale
            default: en_GB
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Translation'

components:
  schemas:
    Translation:
      type: object
      properties:
        id:
          type: integer
        languageKey:
          type: string
        translation:
          type: string
        locale:
          type: string
