// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: translation/v1/translation.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Locale int32

const (
	Locale_LOCALE_UNSPECIFIED Locale = 0
	Locale_LOCALE_DE_DE       Locale = 1
	Locale_LOCALE_EN_GB       Locale = 2
)

// Enum value maps for Locale.
var (
	Locale_name = map[int32]string{
		0: "LOCALE_UNSPECIFIED",
		1: "LOCALE_DE_DE",
		2: "LOCALE_EN_GB",
	}
	Locale_value = map[string]int32{
		"LOCALE_UNSPECIFIED": 0,
		"LOCALE_DE_DE":       1,
		"LOCALE_EN_GB":       2,
	}
)

func (x Locale) Enum() *Locale {
	p := new(Locale)
	*p = x
	return p
}

func (x Locale) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Locale) Descriptor() protoreflect.EnumDescriptor {
	return file_translation_v1_translation_proto_enumTypes[0].Descriptor()
}

func (Locale) Type() protoreflect.EnumType {
	return &file_translation_v1_translation_proto_enumTypes[0]
}

func (x Locale) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Locale.Descriptor instead.
func (Locale) EnumDescriptor() ([]byte, []int) {
	return file_translation_v1_translation_proto_rawDescGZIP(), []int{0}
}

type Translation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LanguageKey   string                 `protobuf:"bytes,1,opt,name=language_key,json=languageKey,proto3" json:"language_key,omitempty"`
	Locale        Locale                 `protobuf:"varint,2,opt,name=locale,proto3,enum=proto.translation.v1.Locale" json:"locale,omitempty"`
	Translation   string                 `protobuf:"bytes,3,opt,name=translation,proto3" json:"translation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Translation) Reset() {
	*x = Translation{}
	mi := &file_translation_v1_translation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Translation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Translation) ProtoMessage() {}

func (x *Translation) ProtoReflect() protoreflect.Message {
	mi := &file_translation_v1_translation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Translation.ProtoReflect.Descriptor instead.
func (*Translation) Descriptor() ([]byte, []int) {
	return file_translation_v1_translation_proto_rawDescGZIP(), []int{0}
}

func (x *Translation) GetLanguageKey() string {
	if x != nil {
		return x.LanguageKey
	}
	return ""
}

func (x *Translation) GetLocale() Locale {
	if x != nil {
		return x.Locale
	}
	return Locale_LOCALE_UNSPECIFIED
}

func (x *Translation) GetTranslation() string {
	if x != nil {
		return x.Translation
	}
	return ""
}

type TranslationList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Translations  []*Translation         `protobuf:"bytes,1,rep,name=translations,proto3" json:"translations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslationList) Reset() {
	*x = TranslationList{}
	mi := &file_translation_v1_translation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationList) ProtoMessage() {}

func (x *TranslationList) ProtoReflect() protoreflect.Message {
	mi := &file_translation_v1_translation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationList.ProtoReflect.Descriptor instead.
func (*TranslationList) Descriptor() ([]byte, []int) {
	return file_translation_v1_translation_proto_rawDescGZIP(), []int{1}
}

func (x *TranslationList) GetTranslations() []*Translation {
	if x != nil {
		return x.Translations
	}
	return nil
}

type LocaleGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locale        Locale                 `protobuf:"varint,1,opt,name=locale,proto3,enum=proto.translation.v1.Locale" json:"locale,omitempty"`
	Translations  *TranslationList       `protobuf:"bytes,2,opt,name=translations,proto3" json:"translations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocaleGroup) Reset() {
	*x = LocaleGroup{}
	mi := &file_translation_v1_translation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocaleGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocaleGroup) ProtoMessage() {}

func (x *LocaleGroup) ProtoReflect() protoreflect.Message {
	mi := &file_translation_v1_translation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocaleGroup.ProtoReflect.Descriptor instead.
func (*LocaleGroup) Descriptor() ([]byte, []int) {
	return file_translation_v1_translation_proto_rawDescGZIP(), []int{2}
}

func (x *LocaleGroup) GetLocale() Locale {
	if x != nil {
		return x.Locale
	}
	return Locale_LOCALE_UNSPECIFIED
}

func (x *LocaleGroup) GetTranslations() *TranslationList {
	if x != nil {
		return x.Translations
	}
	return nil
}

type GroupedTranslations struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*LocaleGroup         `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupedTranslations) Reset() {
	*x = GroupedTranslations{}
	mi := &file_translation_v1_translation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupedTranslations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupedTranslations) ProtoMessage() {}

func (x *GroupedTranslations) ProtoReflect() protoreflect.Message {
	mi := &file_translation_v1_translation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupedTranslations.ProtoReflect.Descriptor instead.
func (*GroupedTranslations) Descriptor() ([]byte, []int) {
	return file_translation_v1_translation_proto_rawDescGZIP(), []int{3}
}

func (x *GroupedTranslations) GetGroups() []*LocaleGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

type GetTranslationByKeyAndLocaleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LanguageKey   string                 `protobuf:"bytes,1,opt,name=language_key,json=languageKey,proto3" json:"language_key,omitempty"`
	Locale        Locale                 `protobuf:"varint,2,opt,name=locale,proto3,enum=proto.translation.v1.Locale" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTranslationByKeyAndLocaleRequest) Reset() {
	*x = GetTranslationByKeyAndLocaleRequest{}
	mi := &file_translation_v1_translation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTranslationByKeyAndLocaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranslationByKeyAndLocaleRequest) ProtoMessage() {}

func (x *GetTranslationByKeyAndLocaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_translation_v1_translation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranslationByKeyAndLocaleRequest.ProtoReflect.Descriptor instead.
func (*GetTranslationByKeyAndLocaleRequest) Descriptor() ([]byte, []int) {
	return file_translation_v1_translation_proto_rawDescGZIP(), []int{4}
}

func (x *GetTranslationByKeyAndLocaleRequest) GetLanguageKey() string {
	if x != nil {
		return x.LanguageKey
	}
	return ""
}

func (x *GetTranslationByKeyAndLocaleRequest) GetLocale() Locale {
	if x != nil {
		return x.Locale
	}
	return Locale_LOCALE_UNSPECIFIED
}

type GetTranslationByKeyAndLocaleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Translation   *Translation           `protobuf:"bytes,1,opt,name=translation,proto3" json:"translation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTranslationByKeyAndLocaleResponse) Reset() {
	*x = GetTranslationByKeyAndLocaleResponse{}
	mi := &file_translation_v1_translation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTranslationByKeyAndLocaleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranslationByKeyAndLocaleResponse) ProtoMessage() {}

func (x *GetTranslationByKeyAndLocaleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_translation_v1_translation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranslationByKeyAndLocaleResponse.ProtoReflect.Descriptor instead.
func (*GetTranslationByKeyAndLocaleResponse) Descriptor() ([]byte, []int) {
	return file_translation_v1_translation_proto_rawDescGZIP(), []int{5}
}

func (x *GetTranslationByKeyAndLocaleResponse) GetTranslation() *Translation {
	if x != nil {
		return x.Translation
	}
	return nil
}

var File_translation_v1_translation_proto protoreflect.FileDescriptor

const file_translation_v1_translation_proto_rawDesc = "" +
	"\n" +
	" translation/v1/translation.proto\x12\x14proto.translation.v1\"\x88\x01\n" +
	"\vTranslation\x12!\n" +
	"\flanguage_key\x18\x01 \x01(\tR\vlanguageKey\x124\n" +
	"\x06locale\x18\x02 \x01(\x0e2\x1c.proto.translation.v1.LocaleR\x06locale\x12 \n" +
	"\vtranslation\x18\x03 \x01(\tR\vtranslation\"X\n" +
	"\x0fTranslationList\x12E\n" +
	"\ftranslations\x18\x01 \x03(\v2!.proto.translation.v1.TranslationR\ftranslations\"\x8e\x01\n" +
	"\vLocaleGroup\x124\n" +
	"\x06locale\x18\x01 \x01(\x0e2\x1c.proto.translation.v1.LocaleR\x06locale\x12I\n" +
	"\ftranslations\x18\x02 \x01(\v2%.proto.translation.v1.TranslationListR\ftranslations\"P\n" +
	"\x13GroupedTranslations\x129\n" +
	"\x06groups\x18\x01 \x03(\v2!.proto.translation.v1.LocaleGroupR\x06groups\"~\n" +
	"#GetTranslationByKeyAndLocaleRequest\x12!\n" +
	"\flanguage_key\x18\x01 \x01(\tR\vlanguageKey\x124\n" +
	"\x06locale\x18\x02 \x01(\x0e2\x1c.proto.translation.v1.LocaleR\x06locale\"k\n" +
	"$GetTranslationByKeyAndLocaleResponse\x12C\n" +
	"\vtranslation\x18\x01 \x01(\v2!.proto.translation.v1.TranslationR\vtranslation*D\n" +
	"\x06Locale\x12\x16\n" +
	"\x12LOCALE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fLOCALE_DE_DE\x10\x01\x12\x10\n" +
	"\fLOCALE_EN_GB\x10\x022\xac\x01\n" +
	"\x12TranslationService\x12\x95\x01\n" +
	"\x1cGetTranslationByKeyAndLocale\x129.proto.translation.v1.GetTranslationByKeyAndLocaleRequest\x1a:.proto.translation.v1.GetTranslationByKeyAndLocaleResponseBAZ?github.com/henok321/translation-service/pb/translation/v1;apiv1b\x06proto3"

var (
	file_translation_v1_translation_proto_rawDescOnce sync.Once
	file_translation_v1_translation_proto_rawDescData []byte
)

func file_translation_v1_translation_proto_rawDescGZIP() []byte {
	file_translation_v1_translation_proto_rawDescOnce.Do(func() {
		file_translation_v1_translation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_translation_v1_translation_proto_rawDesc), len(file_translation_v1_translation_proto_rawDesc)))
	})
	return file_translation_v1_translation_proto_rawDescData
}

var file_translation_v1_translation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_translation_v1_translation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_translation_v1_translation_proto_goTypes = []any{
	(Locale)(0),                                  // 0: proto.translation.v1.Locale
	(*Translation)(nil),                          // 1: proto.translation.v1.Translation
	(*TranslationList)(nil),                      // 2: proto.translation.v1.TranslationList
	(*LocaleGroup)(nil),                          // 3: proto.translation.v1.LocaleGroup
	(*GroupedTranslations)(nil),                  // 4: proto.translation.v1.GroupedTranslations
	(*GetTranslationByKeyAndLocaleRequest)(nil),  // 5: proto.translation.v1.GetTranslationByKeyAndLocaleRequest
	(*GetTranslationByKeyAndLocaleResponse)(nil), // 6: proto.translation.v1.GetTranslationByKeyAndLocaleResponse
}
var file_translation_v1_translation_proto_depIdxs = []int32{
	0, // 0: proto.translation.v1.Translation.locale:type_name -> proto.translation.v1.Locale
	1, // 1: proto.translation.v1.TranslationList.translations:type_name -> proto.translation.v1.Translation
	0, // 2: proto.translation.v1.LocaleGroup.locale:type_name -> proto.translation.v1.Locale
	2, // 3: proto.translation.v1.LocaleGroup.translations:type_name -> proto.translation.v1.TranslationList
	3, // 4: proto.translation.v1.GroupedTranslations.groups:type_name -> proto.translation.v1.LocaleGroup
	0, // 5: proto.translation.v1.GetTranslationByKeyAndLocaleRequest.locale:type_name -> proto.translation.v1.Locale
	1, // 6: proto.translation.v1.GetTranslationByKeyAndLocaleResponse.translation:type_name -> proto.translation.v1.Translation
	5, // 7: proto.translation.v1.TranslationService.GetTranslationByKeyAndLocale:input_type -> proto.translation.v1.GetTranslationByKeyAndLocaleRequest
	6, // 8: proto.translation.v1.TranslationService.GetTranslationByKeyAndLocale:output_type -> proto.translation.v1.GetTranslationByKeyAndLocaleResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_translation_v1_translation_proto_init() }
func file_translation_v1_translation_proto_init() {
	if File_translation_v1_translation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_translation_v1_translation_proto_rawDesc), len(file_translation_v1_translation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_translation_v1_translation_proto_goTypes,
		DependencyIndexes: file_translation_v1_translation_proto_depIdxs,
		EnumInfos:         file_translation_v1_translation_proto_enumTypes,
		MessageInfos:      file_translation_v1_translation_proto_msgTypes,
	}.Build()
	File_translation_v1_translation_proto = out.File
	file_translation_v1_translation_proto_goTypes = nil
	file_translation_v1_translation_proto_depIdxs = nil
}
